### ISSUE TITLE
Post GitHub Actions cleanup

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/manageiq-appliance_console#205]
- [x] Fix tests on Ruby 3.0 and remove fail-fast #206
- [ ] Undo pending specs
  - [ ] PostgresRunner
  - [x] spec/database_admin_spec.rb fails for some weird stream issue only on CI and in act with `true | act 2>&1 | cat`  Removed in #201
- [x] Perhaps remove the TTY hacks?  This might be easier or not needed after #201

**Comment by kbrock** [comment]
may want to consider #207
